/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package Pancake-0.1.0.0 */
#ifndef VERSION_Pancake
#define VERSION_Pancake "0.1.0.0"
#endif /* VERSION_Pancake */
#ifndef MIN_VERSION_Pancake
#define MIN_VERSION_Pancake(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_Pancake */

/* package base-4.11.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.11.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  11 || \
  (major1) == 4 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package flow-1.0.17 */
#ifndef VERSION_flow
#define VERSION_flow "1.0.17"
#endif /* VERSION_flow */
#ifndef MIN_VERSION_flow
#define MIN_VERSION_flow(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 17)
#endif /* MIN_VERSION_flow */

/* package parsec-3.1.13.0 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.13.0"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 13)
#endif /* MIN_VERSION_parsec */

/* package containers-0.5.11.0 */
#ifndef VERSION_containers
#define VERSION_containers "0.5.11.0"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 11)
#endif /* MIN_VERSION_containers */

/* package split-0.2.3.3 */
#ifndef VERSION_split
#define VERSION_split "0.2.3.3"
#endif /* VERSION_split */
#ifndef MIN_VERSION_split
#define MIN_VERSION_split(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_split */

/* package directory-1.3.1.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.1.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_directory */

/* tool alex-3.1.6 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.1.6"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_alex */

/* tool gcc-5.4.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "5.4.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  5 || \
  (major1) == 5 && (major2) <  4 || \
  (major1) == 5 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.4.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.4.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.4.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.4.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.20.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.20.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  20 || \
  (major1) == 2 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool happy-1.19.5 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.19.5"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_happy */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.3 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.3"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool hscolour-1.22 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.22"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  22 || \
  (major1) == 1 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */

/* tool pkg-config-0.29.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.4.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.4.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.26 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.26"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  26 || \
  (major1) == 2 && (major2) == 26 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "Pancake-0.1.0.0-A16bPMzPAYq62C5YN4qnn2-Pancake"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
